apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      type: db
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        type: db
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-secret-mount
              mountPath: /etc/mongo-credentials
            - name: mongo-config-mount
              mountPath: /config
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-secret-mount
          secret:
            secretName: mongo-secret
        - name: mongo-config-mount
          configMap:
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
